### ISSUE TITLE
test-site dashboard query qps issue

### ISSUE THREAD

**Issue by yiyuandao** [DNS-OARC/dsc-datatool#23]
when I visit the demo site(https://dev.dns-oarc.net/dsc-grafana2/dashboard/db/dsc), i found the qps issue.
eg. try 
 set Time Resolution to 1m, then check the bynode qps, got avg qps: 14pps
 set Time Resolution to 5m, t  got avg qps: 66pps
 set Time Resolution to 10m, t  got avg qps: 133pps
 set Time Resolution to 1h, t  got avg qps: 598pps
  
 is the avg qps right or wrong?

  but from the bynode graph, the avg qps in 3hours is less then 20pps
  IMHO, in different Time Resolution, the avg qps should be in the same range.

**Comment by jelu** [comment]
It's wrong, there is an issue with the graphs w.r.t. QPS/PPS. You can also see it if you zoom out. Might have to do with the data being in minute resolutions and the queries are not quite right for that, I just have to find the time to look at it.

**Comment by yiyuandao** [comment]
I checked the query in influxdb,  include 'GROUP BY time($interval)', 
but when influxdb exec the query, the interval depends on the time range, and not the template variable $interval,

eg. 
time range <= last 1d,          interval=1m
time range  =last 2d, last 3d, interval=2m
time range  =last 4d, last 5d,last 6d, interval=2m
time range = last 1w,          interval=5m
time range = last 2w,          interval=15m

**Comment by jelu** [comment]
Does it look better now?
