### ISSUE TITLE
DSC to influxDB failing

### ISSUE THREAD

**Issue by calvinbrowne** [DNS-OARC/dsc-datatool#31]
On the collector side, when collection is done for:
`dataset second_ld_vs_rcode dns Rcode:rcode SecondLD:second_ld replies-only max-cells=50; `

Sometimes queries are received for null names:

```
<array name="second_ld_vs_rcode" dimensions="2" start_time="1556173500" stop_time="1556173560">
  <dimension number="1" type="Rcode"/>
  <dimension number="2" type="SecondLD"/>
  <data>
    <Rcode val="0">
      <SecondLD val="org.za" count="2"/>
      <SecondLD val="" count="2"/>
      <SecondLD val="amazonaws.com" count="1"/
```

which ends up after DSC-datatool as

`second_ld_vs_rcode,server=servername,node=ns.coza.net.za,rcode=5,secondld= value=2 1556174460000000000`

which chokes when fed into 'influx -import' because of the missing value @ "secondld="

dsc-datatool needs to add a null character when encountered, to prevent the influxdb import from breaking.

**Comment by jelu** [comment]
I believe I can fix this quite quickly but I'm having a hard time to find the time to do it as we are ramping up for our annual workshop :/

**Comment by calvinbrowne** [comment]
Any updates on this? Anything I can do/supply to move this forward?

**Comment by jelu** [comment]
Just got back today from a lot of traveling, will look at this ASAP

**Comment by jelu** [comment]
Looking at this now, and a little searching tells that it might have worked before (somewhat):

> You cannot search for nulls in InfluxDB <0.9. You will not be able to insert nulls in Influx >=0.9

It also looks like InfluxDB have much better support for quoting then it did when I first made this :)

**Comment by calvinbrowne** [comment]
Yeah - that was my reading - but then I only read the current influx stuff.

My thinking is that if the field is blank, making it the string "Null" 
would suffice.

My temporary work around was not to process xml files with fields like 
"", and I've been holding back on replacing them with "Null".


--Calvin

**Comment by jelu** [comment]
That was a quick and easy fix, sorry that it took so long.

Can you test using the develop branch or do you need a release? If so, what dist?

**Comment by calvinbrowne** [comment]
As soon as i work out how to clone the development branch, I'll test.

**Comment by jelu** [comment]
```
git clone https://github.com/DNS-OARC/dsc-datatool.git
cd dsc-datatool
git checkout develop
```

**Comment by calvinbrowne** [comment]
looking good on my test stuff - throwing it at some live data - will revert

**Comment by calvinbrowne** [comment]
Right - done and dusted - adding you to my list of people I owe a beer/coffee to.

**Comment by jelu** [comment]
Great to hear :) I will make a release in the coming days.

If you want to support [DNS-OARC](https://www.dns-oarc.net/) and our software please consider [becoming a member](https://www.dns-oarc.net/files/web-brochure.pdf). There is also options to do one-time donation, let me know if so!
