### ISSUE TITLE
dsc-datatool chokes on '...' tld

### ISSUE THREAD

**Issue by calvinbrowne** [DNS-OARC/dsc-datatool#37]
Occasionally, someone manages to send a query to a NS containing '...' as the zone being queries.

This ends up as the following in the xml files:
```
<array name="qtype_vs_tld" dimensions="2" start_time="1562012880" stop_time="1562012940">
   <dimension number="1" type="Qtype"/>
   <dimension number="2" type="TLD"/>
   <data>
     <Qtype val="1" count="374">
       <TLD val="..." count="15"/>
       <TLD val="africa." count="10"/>
       <TLD val="co.za." count="332"/>
       <TLD val="za." count="17"/>
     </Qtype>
```

dsc-datatool dies when encountering this :(

Similar to my previous issue reported in April?

**Comment by jelu** [comment]
No, if `dsc-datatool` dies then this is a different problem, before it was the Influx import that died.

**Comment by jelu** [comment]
Just ran successfully with a `...` entry, no problems at all.
```
# DML
# CONTEXT-DATABASE: dsc
qtype_vs_tld,server=test,node=test,qtype=1,tld=... value=128 1563520560000000000
```
Can you add your output?

**Comment by calvinbrowne** [comment]
ok - this is weird - let me do some more investigation and revert

**Comment by calvinbrowne** [comment]
ok - I found it..... nothing to see here - my fault.

Basically, I was parallelising the imports, and two of my processes were using the same datafile.....
- basically on
" --output ";InfluxDB;file=influx.txt;dml=1;database=testdsc" \"

"influx.txt;" was shared between two import scripts, and naturally, bash doesn't like files changing out from under it.
the error messages varied according to the state the file was in.

Apologies

**Comment by jelu** [comment]
No worry :)
