### ISSUE TITLE
Datatool wants to connect to 192.0.47.8 => www.iana.org

### ISSUE THREAD

**Issue by tonk** [DNS-OARC/dsc-datatool#83]
The dsc-datatool want to connect to `192.0.47.8` which points to `www.iana.org'.
The machine that needs to convert the data has absolutely no direct connection to the internet and will never have so.
How do I stop the datatool connecting to Icann?

**Comment by jelu** [comment]
Make the data available offline, read the manual for options: `man dsc-datatool generator-client_subnet_authority`.
